#!/bin/sh
set -e

udevadm control --reload-rules || echo "Reloading udev failed. You might need to reboot to complete installation." 1>&2
udevadm trigger || echo "Reloading udev failed. You might need to reboot to complete installation." 1>&2

exit 0
