#!/bin/sh
set -e

udevadm control --reload-rules || echo "Reloading udev failed. You will need to reboot to complete uninstallation" 1>&2
udevadm trigger || echo "Reloading udev failed. You will need to reboot to complete uninstallation" 1>&2

exit 0
